# Generated by Django 2.1.5 on 2019-01-09 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190109_0213'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='url',
            field=models.URLField(max_length=255, null=True),
        ),
    ]
