# Generated by Django 2.1.5 on 2019-01-10 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_report_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='civil_rights_violation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='hate_crime',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='police_brutality',
            field=models.BooleanField(default=False),
        ),
    ]
